console.log('👥 USER LOGIN INFORMATION');
console.log('==========================');
console.log('');
console.log('✅ Your system supports logging in with ANY email from the database!');
console.log('');
console.log('📋 KNOWN USERS:');
console.log('');
console.log('1. 👤 Employee User');
console.log('   📧 Email: keshaw390@gmail.com');
console.log('   👑 Role: EMPLOYEE');
console.log('   🔐 Password: Employee@123');
console.log('');
console.log('2. 👤 Admin User');
console.log('   📧 Email: admin@techcorp.com');
console.log('   👑 Role: ADMIN');
console.log('   🔐 Password: Admin@123');
console.log('');
console.log('🔐 LOGIN INSTRUCTIONS:');
console.log('======================');
console.log('');
console.log('You can login with ANY of the above emails using:');
console.log('');
console.log('📋 DEFAULT PASSWORDS:');
console.log('   • All Employees: Employee@123');
console.log('   • All Admins: Admin@123');
console.log('');
console.log('💡 EXAMPLE LOGINS:');
console.log('   • keshaw390@gmail.com / Employee@123');
console.log('   • admin@techcorp.com / Admin@123');
console.log('');
console.log('🎯 QUICK TEST:');
console.log('   1. Open your app: http://localhost:8080');
console.log('   2. Try any email from the list above');
console.log('   3. Use the default password for that role');
console.log('   4. Login successfully!');
console.log('');
console.log('⚠️  NOTE: Your system supports ANY email from the database!');
console.log('    If you add more users, they will also work with the same pattern.');
console.log('');
console.log('🚀 TO ADD MORE USERS:');
console.log('   1. Use the app registration feature');
console.log('   2. Or use the database manager');
console.log('   3. Or run the add user scripts');
console.log('');
console.log('📞 NEED HELP?');
console.log('   Email: Info@serv.co.in');
console.log('   Phone: 9042525258'); 