@echo off
echo Setting up backend...
echo.
echo 1. Generating Prisma client...
npx prisma generate
echo.
echo 2. Pushing database schema...
npx prisma db push
echo.
echo 3. Seeding database with real data...
npx prisma db seed
echo.
echo 4. Starting server...
npm start 