// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCftp3z_bDQneqCSKJwKMzgFDTNQ_GyGNs',
    appId: '1:330461197293:web:602c75d5dd57aa58c8ede4',
    messagingSenderId: '330461197293',
    projectId: 'serv-dev-f2557',
    authDomain: 'serv-dev-f2557.firebaseapp.com',
    storageBucket: 'serv-dev-f2557.firebasestorage.app',
    measurementId: 'G-Q2QXH1JNT4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6i2QPdokffp_OpuixKyd7sjOO-FLOGvQ',
    appId: '1:330461197293:android:922dba5f98e7f9b3c8ede4',
    messagingSenderId: '330461197293',
    projectId: 'serv-dev-f2557',
    storageBucket: 'serv-dev-f2557.firebasestorage.app',
  );
}
