// // lib/main.dart
// import 'package:flutter/material.dart';

// // ✅ Firebase
// import 'package:firebase_core/firebase_core.dart';
// import 'package:firebase_auth/firebase_auth.dart';
// import 'firebase_options.dart'; // generated by FlutterFire CLI

// // ✅ Your pages & models
// import 'package:serv_app/Pagesusers/attendance_model_page.dart';
// import 'package:serv_app/Pagesusers/login_page.dart';
// import 'package:serv_app/Pagesadmin/leave_page.dart';
// import 'package:serv_app/Pagesadmin/leave_form_page.dart';

// Future<void> main() async {
//   WidgetsFlutterBinding.ensureInitialized();

//   // Initialize Firebase for all platforms
//   await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
//   );

//   // Ensure a Firebase user exists (useful for Storage/Firestore rules that require auth)
//   try {
//     if (FirebaseAuth.instance.currentUser == null) {
//       await FirebaseAuth.instance.signInAnonymously();
//     }
//   } catch (e) {
//     // Non-fatal in dev; you can show a dialog/snackbar if you prefer
//     // ignore: avoid_print
//     print('Anonymous sign-in failed: $e');
//   }

//   // 🔥 Dummy Attendance Data (kept as-is)
//   final AttendanceData sampleData = AttendanceData(
//     presentCount: 10,
//     absentCount: 2,
//     leaveCount: 0,
//     lateCheckIn: 0,
//     earlyCheckOut: 2,
//     permissionCount: 0,
//     presentDates: [
//       DateTime(2025, 7, 1),
//       DateTime(2025, 7, 3),
//       DateTime(2025, 7, 4),
//       DateTime(2025, 7, 5),
//       DateTime(2025, 7, 6),
//       DateTime(2025, 7, 7),
//       DateTime(2025, 7, 8),
//       DateTime(2025, 7, 9),
//       DateTime(2025, 7, 10),
//       DateTime(2025, 7, 11),
//     ],
//     absentDates: [DateTime(2025, 7, 2)],
//     totalDays: 12,
//   );

//   runApp(MyApp(attendanceData: sampleData));
// }

// class MyApp extends StatelessWidget {
//   final AttendanceData attendanceData;

//   const MyApp({super.key, required this.attendanceData});

//   @override
//   Widget build(BuildContext context) {
//     final ThemeData myTheme = ThemeData(
//       fontFamily: 'Inter',
//       scaffoldBackgroundColor: const Color(0xFFF8F6FF),
//       cardColor: Colors.white,
//       iconTheme: const IconThemeData(color: Color(0xFF0F3D3E)),
//       textTheme: const TextTheme(
//         bodyMedium: TextStyle(fontSize: 14, color: Colors.black),
//       ),
//       appBarTheme: const AppBarTheme(
//         backgroundColor: Color(0xFF8C6EAF),
//         titleTextStyle: TextStyle(
//           color: Colors.white,
//           fontSize: 18,
//           fontWeight: FontWeight.bold,
//         ),
//         iconTheme: IconThemeData(color: Colors.white),
//         elevation: 2,
//       ),
//       elevatedButtonTheme: ElevatedButtonThemeData(
//         style: ElevatedButton.styleFrom(
//           backgroundColor: const Color(0xFF655193),
//           foregroundColor: Colors.white,
//           padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 12),
//           textStyle: const TextStyle(fontSize: 16),
//         ),
//       ),
//       useMaterial3: true,
//     );

//     return MaterialApp(
//       title: 'SERV App',
//       debugShowCheckedModeBanner: false,
//       theme: myTheme,
//       initialRoute: '/',
//       routes: {
//         '/': (context) => const LoginPage(),
//         '/leave': (context) => const LeavePage(),
//         '/add-leave': (context) => const LeaveFormPage(),
//       },
//     );
//   }
// }
import 'package:flutter/material.dart';

// ✅ Firebase
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'firebase_options.dart'; // generated by FlutterFire CLI

// ✅ Your pages
import 'package:serv_app/Pagesusers/login_page.dart';
import 'package:serv_app/Pagesadmin/leave_page.dart';
import 'package:serv_app/Pagesadmin/leave_form_page.dart';
import 'package:serv_app/Pagesusers/landing_screen.dart';
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  try {
    // Initialize Firebase only if it hasn't been initialized yet
    if (Firebase.apps.isEmpty) {
      await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );
      
      // Optional: ensure there is a FirebaseAuth user (helps with Storage/Firestore rules)
      try {
        if (FirebaseAuth.instance.currentUser == null) {
          await FirebaseAuth.instance.signInAnonymously();
          // ignore: avoid_print
          print('[FirebaseAuth] Anonymous sign-in OK');
        }
      } catch (e) {
        // Non-fatal in dev
        // ignore: avoid_print
        print('Anonymous sign-in failed: $e');
      }
    }
  } catch (e) {
    // ignore: avoid_print
    print('Firebase initialization error: $e');
  }

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    final ThemeData myTheme = ThemeData(
      fontFamily: 'Inter',
      scaffoldBackgroundColor: const Color(0xFFF8F6FF),
      cardColor: Colors.white,
      iconTheme: const IconThemeData(color: Color(0xFF0F3D3E)),
      textTheme: const TextTheme(
        bodyMedium: TextStyle(fontSize: 14, color: Colors.black),
      ),
      appBarTheme: const AppBarTheme(
        backgroundColor: Color(0xFF8C6EAF),
        titleTextStyle: TextStyle(
          color: Colors.white,
          fontSize: 18,
          fontWeight: FontWeight.bold,
        ),
        iconTheme: IconThemeData(color: Colors.white),
        elevation: 2,
      ),
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: const Color(0xFF655193),
          foregroundColor: Colors.white,
          padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 12),
          textStyle: const TextStyle(fontSize: 16),
        ),
      ),
      useMaterial3: true,
    );

    return MaterialApp(
      title: 'SERV App',
      debugShowCheckedModeBanner: false,
      theme: myTheme,
      initialRoute: '/',
      routes: {
        '/': (context) => const LoginPage(),
        // Explicit login route (recommended so you can target it by name)
        '/login': (context) => const LoginPage(),
        '/leave': (context) => const LeavePage(),
        '/add-leave': (context) => const LeaveFormPage(),
        '/landing': (context) => const LandingScreen(),
      },
    );
  }
}
